spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/GoodStorage
    username: root
    password: 33333333
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mustache:
    expose-request-attributes: true

